/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    '2fa': RouteRecordInfo<'2fa', '/2fa', Record<never, never>, Record<never, never>>,
    'academic-years': RouteRecordInfo<'academic-years', '/academic-years', Record<never, never>, Record<never, never>>,
    'attendance-reports': RouteRecordInfo<'attendance-reports', '/attendance-reports', Record<never, never>, Record<never, never>>,
    'attendance-reports-instructor': RouteRecordInfo<'attendance-reports-instructor', '/attendance-reports/instructor', Record<never, never>, Record<never, never>>,
    'attendance-reports-students': RouteRecordInfo<'attendance-reports-students', '/attendance-reports/students', Record<never, never>, Record<never, never>>,
    'classes': RouteRecordInfo<'classes', '/classes', Record<never, never>, Record<never, never>>,
    'classes-join-id': RouteRecordInfo<'classes-join-id', '/classes/join/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'courses': RouteRecordInfo<'courses', '/courses', Record<never, never>, Record<never, never>>,
    'courses-topics': RouteRecordInfo<'courses-topics', '/courses/topics', Record<never, never>, Record<never, never>>,
    'dashboard': RouteRecordInfo<'dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'departments': RouteRecordInfo<'departments', '/departments', Record<never, never>, Record<never, never>>,
    'evaluations': RouteRecordInfo<'evaluations', '/evaluations', Record<never, never>, Record<never, never>>,
    'evaluations-evaluation': RouteRecordInfo<'evaluations-evaluation', '/evaluations/evaluation', Record<never, never>, Record<never, never>>,
    'evaluations-instructor': RouteRecordInfo<'evaluations-instructor', '/evaluations/instructor', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'my-profile': RouteRecordInfo<'my-profile', '/my-profile', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'roles': RouteRecordInfo<'roles', '/roles', Record<never, never>, Record<never, never>>,
    'schools': RouteRecordInfo<'schools', '/schools', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'set-password': RouteRecordInfo<'set-password', '/set-password', Record<never, never>, Record<never, never>>,
    'two-steps-v2': RouteRecordInfo<'two-steps-v2', '/two-steps-v2', Record<never, never>, Record<never, never>>,
    'users': RouteRecordInfo<'users', '/users', Record<never, never>, Record<never, never>>,
    'users-instructor': RouteRecordInfo<'users-instructor', '/users/instructor', Record<never, never>, Record<never, never>>,
    'users-students': RouteRecordInfo<'users-students', '/users/students', Record<never, never>, Record<never, never>>,
  }
}
